# Generated by Django 2.2 on 2021-06-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_scores',
            field=models.CharField(default='0,0,0,0,0', max_length=20, verbose_name='每日成绩走向图'),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_units',
            field=models.CharField(default='0,0,0,0,0', max_length=20, verbose_name='每日单元数走向图'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='studyInfo',
            field=models.CharField(default='暂无', max_length=200, verbose_name='学习情况'),
        ),
    ]
